const data = {
  products: [
    {
      id: 1,
      productName: "ShampooAntiFrizz",
      productUrl: "/productos/shampoo-anti-frizz",
      name: 'UKemp SHAMPOO #Anti-Frizz',
      category: 'shampoo',
      image: '/img/products/sfd_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 2,
      productName: "ShampooAntiFrizz",
      productUrl: "/productos/shampoo-anti-frizz",
      name: 'UKemp SHAMPOO #Anti-Frizz',
      category: 'shampoo',
      image: '/img/products/sfd_400.png',
      size: "650ml",
      price: 180,
      brand: 'UKemp',
    },
    {
      id: 3,
      productName: "ShampooDetox",
      productUrl: "/productos/shampoo-detox",
      name: 'UKemp SHAMPOO Detox',
      category: 'shampoo',
      image: '/img/products/std_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 4,
      productName: "ShampooDetox",
      productUrl: "/productos/shampoo-detox",
      name: 'UKemp SHAMPOO Detox',
      productUrl: "shampoo-detox",
      category: 'shampoo',
      image: '/img/products/std_400.png',
      size: "650ml",
      price: 180,
      brand: 'UKemp',
    },
    {
      id: 5,
      productName: "ShampooLiso4K",
      productUrl: "/productos/shampoo-liso-4k",
      name: 'UKemp SHAMPOO Liso 4K',
      category: 'shampoo',
      image: '/img/products/sl4_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 6,
      productName: "ShampooLiso4K",
      productUrl: "/productos/shampoo-liso-4k",
      name: 'UKemp SHAMPOO Liso 4K',
      category: 'shampoo',
      image: '/img/products/sl4_400.png',
      size: "650ml",
      price: 180,
      brand: 'UKemp',
    },
    {
      id: 7,
      productName: "ShampooRepairBomba",
      productUrl: "/productos/shampoo-repair-bomba",
      name: 'UKemp SHAMPOO Bomba de Proteinas',
      category: 'shampoo',
      image: '/img/products/srb_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 8,
      productName: "ShampooRepairBomba",
      productUrl: "/productos/shampoo-repair-bomba",
      name: 'UKemp SHAMPOO Bomba de Proteinas',
      category: 'shampoo',
      image: '/img/products/srb_400.png',
      size: "650ml",
      price: 180,
      brand: 'UKemp',
    },
    {
      id: 9,
      productName: "ShampooSilver",
      productUrl: "/productos/shampoo-silver",
      name: 'UKemp SHAMPOO Rubio Silver',
      category: 'shampoo',
      image: '/img/products/ss_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 10,
      productName: "ShampooSilver",
      productUrl: "/productos/shampoo-silver",
      name: 'UKemp SHAMPOO Rubio Silver',
      category: 'shampoo',
      image: '/img/products/ss_400.png',
      size: "650ml",
      price: 180,
      brand: 'UKemp',
    },
    {
      id: 11,
      productName: "AcondicionadorAntiFrizz",
      productUrl: "/productos/acondicionador-anti-frizz",
      name: 'UKemp ACONDICIONADOR #Anti-Frizz',
      category: 'acondicionador',
      image: '/img/products/cfd_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 12,
      productName: "AcondicionadorDetox",
      productUrl: "/productos/acondicionador-detox",
      name: 'UKemp ACONDICIONADOR Detox',
      category: 'acondicionador',
      image: '/img/products/ctd_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 13,
      productName: "AcondicionadorLiso4K",
      productUrl: "/productos/acondicionador-liso-4k",
      name: 'UKemp ACONDICIONADOR Liso 4K',
      category: 'acondicionador',
      image: '/img/products/cl4_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 14,
      productName: "AcondicionadorRepairBomba",
      productUrl: "/productos/acondicionador-repair-bomba",
      name: 'UKemp ACONDICIONADOR Bomba de Proteinas',
      category: 'acondicionador',
      image: '/img/products/crb_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 15,
      productName: "AcondicionadorSilver",
      productUrl: "/productos/acondicionador-silver",
      name: 'UKemp ACONDICIONADOR Silver',
      category: 'acondicionador',
      image: '/img/products/cs_400.png',
      size: "400ml",
      price: 120,
      brand: 'UKemp',
    },
    {
      id: 16,
      productName: "MascaraCapilar",
      productUrl: "/productos/mascara-capilar",
      name: 'UKemp MASCARA CAPILAR',
      category: 'mascara capilar',
      image: '/img/products/mc_200.png',
      size: "200ml",
      price: 150,
      brand: 'UKemp',
    },
    {
      id: 17,
      productName: "MascaraCapilarSilver",
      productUrl: "/productos/mascara-capilar-silver",
      name: 'UKemp MASCARA CAPILAR Silver',
      category: 'mascara capilar',
      image: '/img/products/mcs_200.png',
      size: "200ml",
      price: 150,
      brand: 'UKemp',
    },
    {
      id: 18,
      productName: "CremaDeManosAgua",
      productUrl: "/productos/crema-de-manos-agua",
      name: 'UKemp FUERZAS DE LA NATURALEZA Agua',
      category: 'Skin Care',
      image: '/img/products/CR_Agua.png',
      size: "50g",
      price: 100,
      brand: 'UKemp',
    },
    {
      id: 19,
      productName: "CremaDeManosAire",
      productUrl: "/productos/crema-de-manos-aire",
      name: 'UKemp FUERZAS DE LA NATURALEZA Aire',
      category: 'Skin Care',
      image: '/img/products/CR_Aire.png',
      size: "50g",
      price: 100,
      brand: 'UKemp',
    },
    {
      id: 20,
      productName: "CremaDeManosFuego",
      productUrl: "/productos/crema-de-manos-fuego",
      name: 'UKemp FUERZAS DE LA NATURALEZA Fuego',
      category: 'Skin Care',
      image: '/img/products/CR_Fuego.png',
      size: "50g",
      price: 100,
      brand: 'UKemp',
    },
    {
      id: 21,
      productName: "CremaDeManosTierra",
      productUrl: "/productos/crema-de-manos-tierra",
      name: 'UKemp FUERZAS DE LA NATURALEZA Tierra',
      category: 'Skin Care',
      image: '/img/products/CR_Tierra.png',
      size: "50g",
      price: 100,
      brand: 'UKemp',
    },
  ],
};
export default data;